import json

with open("notebooks/baseline_notebook/residual_relu_analytic_jacobian.ipynb", "r") as f:
    nb = json.load(f)

new_source = [
    "import torch\n",
    "import matplotlib.pyplot as plt\n",
    "from homeomorphism import jacobian\n",
    "\n",
    "eps = 0.1\n",
    "W1 = torch.eye(2)\n",
    "W2 = eps * torch.eye(2)\n",
    "b1 = torch.zeros(2)\n",
    "\n",
    "def block_vec(h):\n",
    "    \"\"\"Reference implementation for a single vector h of shape (d,).\"\"\"\n",
    "    z = W1 @ h + b1\n",
    "    return h + W2 @ torch.relu(z)\n",
    "\n",
    "def block_seq(h_seq):\n",
    "    \"\"\"Idiomatic PyTorch implementation vectorized over sequence length (T, d).\"\"\"\n",
    "    z = h_seq @ W1.T + b1\n",
    "    return h_seq + torch.relu(z) @ W2.T\n",
    "\n",
    "test_points = [torch.tensor([1.0, 1.0]), torch.tensor([-1.0, -1.0]), torch.tensor([1.0, -1.0])]\n",
    "labels = ['both active', 'both inactive', 'mixed']\n",
    "numeric_logdets = []\n",
    "analytic_logdets = []\n",
    "\n",
    "for h, lbl in zip(test_points, labels):\n",
    "    h_seq = h.to(torch.float32).view(1, -1)\n",
    "    bj, per_diag = jacobian.build_jacobian(\n",
    "        block_seq, h_seq, scope='diagonal', evaluate='per_diagonal_slogdet'\n",
    "    )\n",
    "    sign, logabs = per_diag[0]\n",
    "    J = bj[(0, 0)]\n",
    "    \n",
    "    active = (h > 0).to(torch.float32)\n",
    "    analytic_diag = 1.0 + eps * active\n",
    "    analytic_log = torch.log(analytic_diag).sum().item()\n",
    "    \n",
    "    # Calculate condition number analytically to verify `torch.linalg.cond`\n",
    "    analytic_cond = (torch.max(analytic_diag) / torch.min(analytic_diag)).item()\n",
    "    cond = torch.linalg.cond(J).item()\n",
    "    \n",
    "    numeric_logdets.append(float(logabs.item()))\n",
    "    analytic_logdets.append(analytic_log)\n",
    "    \n",
    "    print(\n",
    "        f\"{lbl:14s} | sign={int(sign.item()):+d} | \"\n",
    "        f\"numeric log|det|={float(logabs):+.6f} | analytic={analytic_log:+.6f} | \"\n",
    "        f\"num cond={cond:.4f} | anal cond={analytic_cond:.4f}\"\n",
    "    )\n",
    "\n",
    "x = range(len(labels))\n",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n",
    "\n",
    "# Plot 1: log|det|\n",
    "ax1.plot(x, numeric_logdets, marker='o', label='numeric (jacobian)')\n",
    "ax1.plot(x, analytic_logdets, marker='s', label='analytic')\n",
    "ax1.set_xticks(list(x))\n",
    "ax1.set_xticklabels(labels, rotation=15)\n",
    "ax1.set_ylabel('log|det J|')\n",
    "ax1.set_title('log|det J|: Numeric vs Analytic')\n",
    "ax1.grid(alpha=0.3)\n",
    "ax1.legend()\n",
    "\n",
    "# Plot 2: Absolute Error\n",
    "errors = [abs(n - a) for n, a in zip(numeric_logdets, analytic_logdets)]\n",
    "ax2.bar(x, errors, color='tomato')\n",
    "ax2.set_xticks(list(x))\n",
    "ax2.set_xticklabels(labels, rotation=15)\n",
    "ax2.set_ylabel('Absolute Error')\n",
    "ax2.set_title('Numeric precision error')\n",
    "ax2.grid(alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
]

nb["cells"][1]["source"] = new_source

with open("notebooks/baseline_notebook/residual_relu_analytic_jacobian.ipynb", "w") as f:
    json.dump(nb, f, indent=1)
